name: yesilsepet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.2.0
  google_generative_ai: ^0.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/grocery.jpeg
    - assets/default_profile_picture.webp
    - assets/google-logo.png
    - assets/recipe.jpg
    - assets/dessert.jpg
    - assets/dessert2.jpg
    - assets/surprise.png
    - assets/images/apple.webp
    - assets/images/broccoli.png
    - assets/images/yemek_photo.webp
    - assets/adam.jpeg


  fonts:
    - family: Nunito
      fonts:
        - asset: assets/font/Nunito-Bold.ttf
        - asset: assets/font/Nunito-Italic.ttf
        - asset: assets/font/Nunito-BoldItalic.ttf

  uses-material-design: true