// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFZgFX-S8OY1V56pH6r7nBcdDYfJ9_AIA',
    appId: '1:859560334690:web:52e168e661941b83d7c83b',
    messagingSenderId: '859560334690',
    projectId: 'suup-5bad6',
    authDomain: 'suup-5bad6.firebaseapp.com',
    storageBucket: 'suup-5bad6.firebasestorage.app',
    measurementId: 'G-XBBP83J2CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM6xE8J2njCkc9rSQ9eUysVFCM8C3gXVY',
    appId: '1:859560334690:android:7eb56e3278d5a4f2d7c83b',
    messagingSenderId: '859560334690',
    projectId: 'suup-5bad6',
    storageBucket: 'suup-5bad6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG4vJ5BUBi1xsNej71rMvwpnVxL6ZwkVM',
    appId: '1:859560334690:ios:4776f2c11cdd2a9ed7c83b',
    messagingSenderId: '859560334690',
    projectId: 'suup-5bad6',
    storageBucket: 'suup-5bad6.firebasestorage.app',
    iosBundleId: 'com.example.yesilsepet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG4vJ5BUBi1xsNej71rMvwpnVxL6ZwkVM',
    appId: '1:859560334690:ios:4776f2c11cdd2a9ed7c83b',
    messagingSenderId: '859560334690',
    projectId: 'suup-5bad6',
    storageBucket: 'suup-5bad6.firebasestorage.app',
    iosBundleId: 'com.example.yesilsepet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFZgFX-S8OY1V56pH6r7nBcdDYfJ9_AIA',
    appId: '1:859560334690:web:81507507fa8f866ad7c83b',
    messagingSenderId: '859560334690',
    projectId: 'suup-5bad6',
    authDomain: 'suup-5bad6.firebaseapp.com',
    storageBucket: 'suup-5bad6.firebasestorage.app',
    measurementId: 'G-6F7WN3B2SM',
  );
}
